import { RouteNode } from "../types";
import path from "node:path";

export function generateRouteFilesSource(nodes: RouteNode[], outDir: string): string {
  const imports: string[] = [];
  
  function traverse(nodes: RouteNode[]) {
    for (const node of nodes) {
      if (node.pagePath) {
        const fpOrig = node.pagePath.replace(/\\/g, "/");
        let relPath = path.relative(outDir, node.pagePath).replace(/\\/g, "/");
        if (!relPath.startsWith(".")) relPath = "./" + relPath;
        imports.push(`  "${fpOrig}": () => import("${relPath}")`);
      }
      if (node.layoutPath) {
        const fpOrig = node.layoutPath.replace(/\\/g, "/");
        let relPath = path.relative(outDir, node.layoutPath).replace(/\\/g, "/");
        if (!relPath.startsWith(".")) relPath = "./" + relPath;
        imports.push(`  "${fpOrig}": () => import("${relPath}")`);
      }
      if (node.middlewarePath) {
        const fpOrig = node.middlewarePath.replace(/\\/g, "/");
        let relPath = path.relative(outDir, node.middlewarePath).replace(/\\/g, "/");
        if (!relPath.startsWith(".")) relPath = "./" + relPath;
        imports.push(`  "${fpOrig}": () => import("${relPath}")`);
      }
      if (node.children) {
        traverse(node.children);
      }
    }
  }

  traverse(nodes);

  return `// Auto-generated by @amazing-router/core
export const routeFiles: Record<string, () => Promise<any>> = {
${imports.join(",\n")}
};
`;
}
