import { RouteNode } from "../types";

export function generateRouteFilesSource(nodes: RouteNode[]): string {
  const imports: string[] = [];
  
  function traverse(nodes: RouteNode[]) {
    for (const node of nodes) {
      if (node.pagePath) {
        const fp = node.pagePath.replace(/\\/g, "/");
        imports.push(`  "${fp}": () => import("${fp}")`);
      }
      if (node.layoutPath) {
        const fp = node.layoutPath.replace(/\\/g, "/");
        imports.push(`  "${fp}": () => import("${fp}")`);
      }
      if (node.middlewarePath) {
        // middleware is server side usually, but maybe they import it
        const fp = node.middlewarePath.replace(/\\/g, "/");
        imports.push(`  "${fp}": () => import("${fp}")`);
      }
      if (node.children) {
        traverse(node.children);
      }
    }
  }

  traverse(nodes);

  return `// Auto-generated by @amazing-router/core
export const routeFiles: Record<string, () => Promise<any>> = {
${imports.join(",\n")}
};
`;
}
